# Generated by Django 3.2 on 2021-05-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='header',
            field=models.ImageField(default='header.jpg', upload_to='users/headers/'),
        ),
    ]
