# Generated by Django 3.2 on 2021-05-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_header'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('created',)},
        ),
    ]
