# Generated by Django 3.2 on 2021-05-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20210509_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mention',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
