# Generated by Django 3.2 on 2021-05-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_alter_tweet_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mention',
            name='body',
            field=models.CharField(max_length=280, verbose_name='mention'),
        ),
    ]
