# Generated by Django 3.2 on 2021-05-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_alter_mention_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mention',
            old_name='body',
            new_name='mention_body',
        ),
    ]
