# Generated by Django 3.2 on 2021-05-10 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_rename_body_mention_mention_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mention',
            old_name='mention_body',
            new_name='mention',
        ),
    ]
